from django.urls import path
from .import views
urlpatterns = [
    path('',views.firstreg,name='firstreg'),
    path('first/',views.first,name='first'),
    path('course/',views.course,name='course'),
    path('course/cse/',views.cse,name='cse'),
    path('creator/',views.newadmin,name='newadmin'),
    path('userprofile/',views.userprofile,name='userprofile'),
    path('logout/',views.user_logout,name='user_logout'),
    path('verifying/',views.check_status,name='check_status'),
    path('mail_checking/',views.mail_checking,name='mail_checking'),
    path('mail_checking/comparing_mail/',views.comparing_mail,name='comparing_mail'),
    path('updating_password/',views.updating_password,name='updating_password'),
    path('updating_password/importing_password/',views.importing_password,name='importing_password'),
    path('faculty/',views.faculty,name='faculty'),
    path('faculty/facultyaccess/',views.facultyaccess,name='facultyaccess'),
    path('faculty/facultyaccess/pdf_links/',views.pdf_links,name='pdf_links'),
    path('faculty/facultyaccess/pdf_links/delete/<str:filename>',views.delete,name='delete'),
    path('faculty/facultyaccess/pdf_links/add/',views.add,name='add'),
    path('faculty/facultyaccess/pdf_links/add/addlink/',views.addlink,name='addlink'),
    path('faculty/fac_logout/',views.fac_logout,name='fac_logout'),
    path('createacnt/',views.createacnt,name='createacnt'),
    path('createacnt/creating/',views.creating,name='creating'),
    path('upload/',views.userinp,name='userinp'),
    path('upload/userfileinp/',views.userfileinp,name='userfileinp'),
    #path('first/',views.wrongmessage,name='wrongmessage'),
    #path('course/',views.pharma,name='pharma'),
    #path('course/',views.law,name='law'),
    #path('testing/',views.manage,name='manage'),
    #path('testing/fileip/',views.fileip,name='fileip'),
    #path('setcookie/',views.setcookie,name='setcookie'),
    #path('first/cse/',views.cse,name='cse'),
    #path('course/',views.btech,name='btech'),
    #path('course/<str:name>',views.files,name='files'),
]

