# Generated by Django 4.0.5 on 2022-07-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='reg',
            new_name='regstration',
        ),
    ]
